DROP TABLE IF EXISTS Projects0 CASCADE;
DROP TABLE IF EXISTS Projects1 CASCADE;
DROP TABLE IF EXISTS Projects2 CASCADE;
DROP TABLE IF EXISTS Projects3 CASCADE;
DROP TABLE IF EXISTS Projects4 CASCADE;

DROP TABLE IF EXISTS Shows0 CASCADE;
DROP TABLE IF EXISTS Shows1 CASCADE;
DROP TABLE IF EXISTS Shows2 CASCADE;

DROP TABLE IF EXISTS Rentals0 CASCADE;
DROP TABLE IF EXISTS Rentals1 CASCADE;
DROP TABLE IF EXISTS Rentals2 CASCADE;
DROP TABLE IF EXISTS Rentals3 CASCADE;

DROP TABLE IF EXISTS Matches0 CASCADE;
DROP TABLE IF EXISTS Matches1 CASCADE;
DROP TABLE IF EXISTS Matches2 CASCADE;
DROP TABLE IF EXISTS Matches3 CASCADE;
DROP TABLE IF EXISTS Matches4 CASCADE;

DROP TABLE IF EXISTS Boats0 CASCADE;
DROP TABLE IF EXISTS Boats1 CASCADE;

-- Projects
---- Tables
CREATE TABLE Projects1 (
    MID INT NOT NULL,
    MN VARCHAR(50) NOT NULL,
    PRIMARY KEY (MID)
);

CREATE TABLE Projects2 (
    ID INT NOT NULL,
    MID INT NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (MID) REFERENCES Projects1 (MID)
);

CREATE TABLE Projects3 (
    PID INT NOT NULL,
    PN VARCHAR(50) NOT NULL,
    PRIMARY KEY (PID)
);

CREATE TABLE Projects4 (
    SID INT NOT NULL,
    SN VARCHAR(50) NOT NULL,
    PRIMARY KEY (SID)
);

CREATE TABLE Projects0 (
    ID INT NOT NULL,
    PID INT NOT NULL,
    SID INT NOT NULL,
    PRIMARY KEY (ID, PID, SID),
    FOREIGN KEY (ID) REFERENCES Projects2 (ID),
    FOREIGN KEY (PID) REFERENCES Projects3 (PID),
    FOREIGN KEY (SID) REFERENCES Projects4 (SID)
);

---- Inserts
INSERT INTO Projects1
SELECT DISTINCT MID, MN
FROM Projects;

INSERT INTO Projects2
SELECT DISTINCT ID, MID
FROM Projects;

INSERT INTO Projects3
SELECT DISTINCT PID, PN
FROM Projects;

INSERT INTO Projects4
SELECT DISTINCT SID, SN
FROM Projects;

INSERT INTO Projects0
SELECT DISTINCT ID, PID, SID
FROM Projects;

-- Shows
---- Tables
CREATE TABLE Shows1 (
    SID INT NOT NULL,
    TI VARCHAR(50) NOT NULL,
    RA VARCHAR(50) NOT NULL,
    IMBD FLOAT NULL,
    PRIMARY KEY (SID)
);

CREATE TABLE Shows2 (
    UID INT NOT NULL,
    UN VARCHAR(50) NOT NULL,
    PRIMARY KEY (UID)
);

CREATE TABLE Shows0 (
    SID INT NOT NULL,
    UID INT NOT NULL,
    S INT NOT NULL,
    PRIMARY KEY (SID,UID),
    FOREIGN KEY (SID) REFERENCES Shows1 (SID),
    FOREIGN KEY (UID) REFERENCES Shows2 (UID)
);

---- Inserts
INSERT INTO Shows1
SELECT DISTINCT SID, TI, RA, IMDB
FROM Shows;

INSERT INTO Shows2
SELECT DISTINCT  UID, UN
FROM Shows;

INSERT INTO Shows0
SELECT DISTINCT SID, UID, S
FROM Shows;

-- Rental
--- Tables

CREATE TABLE Rentals1(
    PID INT NOT NULL,
    PN VARCHAR NOT NULL,
    S INT NOT NULL,
    PRIMARY KEY(PID)
);

CREATE TABLE Rentals2(
    HID INT NOT NULL,
    HS VARCHAR NOT NULL,
    HZ INT NOT NULL,
    PRIMARY KEY(HID)
);

CREATE TABLE Rentals3(
    HZ INT NOT NULL,
    HC VARCHAR NOT NULL,
    PRIMARY KEY (HZ),
    FOREIGN KEY (HZ) REFERENCES Rentals2 (HZ)
);

CREATE TABLE Rentals0 ( 
    PID INT NOT NULL,
    HID INT NOT NULL,
    PRIMARY KEY (PID, HID),
    FOREIGN KEY (PID) REFERENCES Rentals1 (PID),
    FOREIGN KEY (HID) REFERENCES Rentals2 (HID)
);

INSERT INTO Rentals1
SELECT DISTINCT PID, PN, S
FROM Rentals;

INSERT INTO Rentals2
SELECT DISTINCT HID, HS, HZ
FROM Rentals;

INSERT INTO Rentals3
SELECT DISTINCT HZ, HC
FROM Rentals;

INSERT INTO Rentals0
SELECT DISTINCT PID, HID
FROM Rentals;

CREATE TABLE Matches1(
    MID INT NOT NULL,
    D DATE NOT NULL,
    H INT,
    A INT,
    PRIMARY KEY (MID)
);

CREATE TABLE Matches2(
    HID INT NOT NULL,
    HN VARCHAR NOT NULL,
    PRIMARY KEY (HID)
);

CREATE TABLE Matches3(
    AID INT NOT NULL,
    AN VARCHAR NOT NULL,
    PRIMARY KEY (AID)
);

CREATE TABLE Matches4(
    RID INT NOT NULL,
    RN VARCHAR NOT NULL,
    PRIMARY KEY (RID)
);

CREATE TABLE Matches0(
    MID INT NOT NULL,
    HID INT NOT NULL,
    AID INT NOT NULL,
    RID INT NOT NULL,
    PRIMARY KEY (MID),
    FOREIGN KEY (MID) REFERENCES Matches1 (MID),
    FOREIGN KEY (HID) REFERENCES Matches2 (HID),
    FOREIGN KEY (AID) REFERENCES Matches3 (AID),
    FOREIGN KEY (RID) REFERENCES Matches4 (RID)
);

INSERT INTO Matches1
SELECT DISTINCT MID, D, H, A 
FROM Matches;

INSERT INTO Matches2
SELECT DISTINCT HID, HN
FROM Matches;

INSERT INTO Matches3
SELECT DISTINCT AID, AN
FROM Matches;

INSERT INTO Matches4
SELECT DISTINCT RID, RN
FROM Matches;

INSERT INTO Matches0
SELECT DISTINCT MID, HID, AID, RID
FROM Matches;

CREATE TABLE Boats1(
    Z INT NOT NULL,
    ZN VARCHAR NOT NULL,
    PRIMARY KEY (Z)
);

CREATE TABLE Boats0(
    BL INT NOT NULL,
    BNo INT NOT NULL,
    Z INT NOT NULL,
    PRIMARY KEY (BL, BNo),
    FOREIGN KEY (Z) REFERENCES Boats1 (Z)
);

INSERT INTO Boats1
SELECT DISTINCT Z, ZN
FROM Boats;

INSERT INTO Boats0
SELECT DISTINCT BL, BNo, Z
FROM Boats;
